// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: logwise-vector.proto
// Protobuf Java Version: 4.33.0

package com.logwise.spark.protobuf;

@com.google.protobuf.Generated
public final class LogwiseVector extends com.google.protobuf.GeneratedFile {
  private LogwiseVector() {}

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 0,
        /* suffix= */ "",
        "LogwiseVector");
  }

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_logwise_vector_logs_VectorLogs_descriptor;
  static final com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_logwise_vector_logs_VectorLogs_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\024logwise-vector.proto\022\023logwise.vector.l"
          + "ogs\032\037google/protobuf/timestamp.proto\"u\n\n"
          + "VectorLogs\022\024\n\014service_name\030\001 \001(\t\022\017\n\007mess"
          + "age\030\002 \001(\t\022\021\n\tlog_level\030\003 \001(\t\022-\n\ttimestam"
          + "p\030\004 \001(\0132\032.google.protobuf.TimestampB\036\n\032c"
          + "om.logwise.spark.protobufP\001b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.protobuf.TimestampProto.getDescriptor(),
            });
    internal_static_logwise_vector_logs_VectorLogs_descriptor = getDescriptor().getMessageType(0);
    internal_static_logwise_vector_logs_VectorLogs_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_logwise_vector_logs_VectorLogs_descriptor,
            new java.lang.String[] {
              "ServiceName", "Message", "LogLevel", "Timestamp",
            });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
