// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vector_logs.proto
// Protobuf Java Version: 4.33.0

package com.logwise.spark.protobuf;

/** Protobuf type {@code logcentral.logs.VectorLogs} */
@com.google.protobuf.Generated
public final class VectorLogs extends com.google.protobuf.GeneratedMessage
    implements
    // @@protoc_insertion_point(message_implements:logcentral.logs.VectorLogs)
    VectorLogsOrBuilder {
  private static final long serialVersionUID = 0L;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 0,
        /* suffix= */ "",
        "VectorLogs");
  }

  // Use VectorLogs.newBuilder() to construct.
  private VectorLogs(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }

  private VectorLogs() {
    message_ = "";
    env_ = "";
    serviceName_ = "";
    componentName_ = "";
    hostname_ = "";
    ddsource_ = "";
    sourceType_ = "";
    status_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.logwise.spark.protobuf.VectorLogsOuterClass
        .internal_static_logcentral_logs_VectorLogs_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 2:
        return internalGetDdtags();
      case 11:
        return internalGetExtra();
      default:
        throw new RuntimeException("Invalid map field number: " + number);
    }
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.logwise.spark.protobuf.VectorLogsOuterClass
        .internal_static_logcentral_logs_VectorLogs_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.logwise.spark.protobuf.VectorLogs.class,
            com.logwise.spark.protobuf.VectorLogs.Builder.class);
  }

  private int bitField0_;
  public static final int MESSAGE_FIELD_NUMBER = 1;

  @SuppressWarnings("serial")
  private volatile java.lang.Object message_ = "";

  /**
   * <code>string message = 1;</code>
   *
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }

  /**
   * <code>string message = 1;</code>
   *
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DDTAGS_FIELD_NUMBER = 2;

  private static final class DdtagsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<java.lang.String, java.lang.String> defaultEntry =
        com.google.protobuf.MapEntry.<java.lang.String, java.lang.String>newDefaultInstance(
            com.logwise.spark.protobuf.VectorLogsOuterClass
                .internal_static_logcentral_logs_VectorLogs_DdtagsEntry_descriptor,
            com.google.protobuf.WireFormat.FieldType.STRING,
            "",
            com.google.protobuf.WireFormat.FieldType.STRING,
            "");
  }

  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<java.lang.String, java.lang.String> ddtags_;

  private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetDdtags() {
    if (ddtags_ == null) {
      return com.google.protobuf.MapField.emptyMapField(DdtagsDefaultEntryHolder.defaultEntry);
    }
    return ddtags_;
  }

  public int getDdtagsCount() {
    return internalGetDdtags().getMap().size();
  }

  /** <code>map&lt;string, string&gt; ddtags = 2;</code> */
  @java.lang.Override
  public boolean containsDdtags(java.lang.String key) {
    if (key == null) {
      throw new NullPointerException("map key");
    }
    return internalGetDdtags().getMap().containsKey(key);
  }

  /** Use {@link #getDdtagsMap()} instead. */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getDdtags() {
    return getDdtagsMap();
  }

  /** <code>map&lt;string, string&gt; ddtags = 2;</code> */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getDdtagsMap() {
    return internalGetDdtags().getMap();
  }

  /** <code>map&lt;string, string&gt; ddtags = 2;</code> */
  @java.lang.Override
  public /* nullable */ java.lang.String getDdtagsOrDefault(
      java.lang.String key,
      /* nullable */
      java.lang.String defaultValue) {
    if (key == null) {
      throw new NullPointerException("map key");
    }
    java.util.Map<java.lang.String, java.lang.String> map = internalGetDdtags().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }

  /** <code>map&lt;string, string&gt; ddtags = 2;</code> */
  @java.lang.Override
  public java.lang.String getDdtagsOrThrow(java.lang.String key) {
    if (key == null) {
      throw new NullPointerException("map key");
    }
    java.util.Map<java.lang.String, java.lang.String> map = internalGetDdtags().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp timestamp_;

  /**
   * <code>.google.protobuf.Timestamp timestamp = 3;</code>
   *
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return ((bitField0_ & 0x00000001) != 0);
  }

  /**
   * <code>.google.protobuf.Timestamp timestamp = 3;</code>
   *
   * @return The timestamp.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimestamp() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }

  /** <code>.google.protobuf.Timestamp timestamp = 3;</code> */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }

  public static final int ENV_FIELD_NUMBER = 4;

  @SuppressWarnings("serial")
  private volatile java.lang.Object env_ = "";

  /**
   * <code>string env = 4;</code>
   *
   * @return The env.
   */
  @java.lang.Override
  public java.lang.String getEnv() {
    java.lang.Object ref = env_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      env_ = s;
      return s;
    }
  }

  /**
   * <code>string env = 4;</code>
   *
   * @return The bytes for env.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getEnvBytes() {
    java.lang.Object ref = env_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      env_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVICE_NAME_FIELD_NUMBER = 5;

  @SuppressWarnings("serial")
  private volatile java.lang.Object serviceName_ = "";

  /**
   * <code>string service_name = 5;</code>
   *
   * @return The serviceName.
   */
  @java.lang.Override
  public java.lang.String getServiceName() {
    java.lang.Object ref = serviceName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serviceName_ = s;
      return s;
    }
  }

  /**
   * <code>string service_name = 5;</code>
   *
   * @return The bytes for serviceName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getServiceNameBytes() {
    java.lang.Object ref = serviceName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      serviceName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMPONENT_NAME_FIELD_NUMBER = 6;

  @SuppressWarnings("serial")
  private volatile java.lang.Object componentName_ = "";

  /**
   * <code>string component_name = 6;</code>
   *
   * @return The componentName.
   */
  @java.lang.Override
  public java.lang.String getComponentName() {
    java.lang.Object ref = componentName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      componentName_ = s;
      return s;
    }
  }

  /**
   * <code>string component_name = 6;</code>
   *
   * @return The bytes for componentName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getComponentNameBytes() {
    java.lang.Object ref = componentName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      componentName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HOSTNAME_FIELD_NUMBER = 7;

  @SuppressWarnings("serial")
  private volatile java.lang.Object hostname_ = "";

  /**
   * <code>optional string hostname = 7;</code>
   *
   * @return Whether the hostname field is set.
   */
  @java.lang.Override
  public boolean hasHostname() {
    return ((bitField0_ & 0x00000002) != 0);
  }

  /**
   * <code>optional string hostname = 7;</code>
   *
   * @return The hostname.
   */
  @java.lang.Override
  public java.lang.String getHostname() {
    java.lang.Object ref = hostname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hostname_ = s;
      return s;
    }
  }

  /**
   * <code>optional string hostname = 7;</code>
   *
   * @return The bytes for hostname.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getHostnameBytes() {
    java.lang.Object ref = hostname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      hostname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DDSOURCE_FIELD_NUMBER = 8;

  @SuppressWarnings("serial")
  private volatile java.lang.Object ddsource_ = "";

  /**
   * <code>optional string ddsource = 8;</code>
   *
   * @return Whether the ddsource field is set.
   */
  @java.lang.Override
  public boolean hasDdsource() {
    return ((bitField0_ & 0x00000004) != 0);
  }

  /**
   * <code>optional string ddsource = 8;</code>
   *
   * @return The ddsource.
   */
  @java.lang.Override
  public java.lang.String getDdsource() {
    java.lang.Object ref = ddsource_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ddsource_ = s;
      return s;
    }
  }

  /**
   * <code>optional string ddsource = 8;</code>
   *
   * @return The bytes for ddsource.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getDdsourceBytes() {
    java.lang.Object ref = ddsource_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      ddsource_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCE_TYPE_FIELD_NUMBER = 9;

  @SuppressWarnings("serial")
  private volatile java.lang.Object sourceType_ = "";

  /**
   * <code>optional string source_type = 9;</code>
   *
   * @return Whether the sourceType field is set.
   */
  @java.lang.Override
  public boolean hasSourceType() {
    return ((bitField0_ & 0x00000008) != 0);
  }

  /**
   * <code>optional string source_type = 9;</code>
   *
   * @return The sourceType.
   */
  @java.lang.Override
  public java.lang.String getSourceType() {
    java.lang.Object ref = sourceType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sourceType_ = s;
      return s;
    }
  }

  /**
   * <code>optional string source_type = 9;</code>
   *
   * @return The bytes for sourceType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSourceTypeBytes() {
    java.lang.Object ref = sourceType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      sourceType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 10;

  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";

  /**
   * <code>optional string status = 10;</code>
   *
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return ((bitField0_ & 0x00000010) != 0);
  }

  /**
   * <code>optional string status = 10;</code>
   *
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }

  /**
   * <code>optional string status = 10;</code>
   *
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXTRA_FIELD_NUMBER = 11;

  private static final class ExtraDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<java.lang.String, java.lang.String> defaultEntry =
        com.google.protobuf.MapEntry.<java.lang.String, java.lang.String>newDefaultInstance(
            com.logwise.spark.protobuf.VectorLogsOuterClass
                .internal_static_logcentral_logs_VectorLogs_ExtraEntry_descriptor,
            com.google.protobuf.WireFormat.FieldType.STRING,
            "",
            com.google.protobuf.WireFormat.FieldType.STRING,
            "");
  }

  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<java.lang.String, java.lang.String> extra_;

  private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetExtra() {
    if (extra_ == null) {
      return com.google.protobuf.MapField.emptyMapField(ExtraDefaultEntryHolder.defaultEntry);
    }
    return extra_;
  }

  public int getExtraCount() {
    return internalGetExtra().getMap().size();
  }

  /** <code>map&lt;string, string&gt; extra = 11;</code> */
  @java.lang.Override
  public boolean containsExtra(java.lang.String key) {
    if (key == null) {
      throw new NullPointerException("map key");
    }
    return internalGetExtra().getMap().containsKey(key);
  }

  /** Use {@link #getExtraMap()} instead. */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getExtra() {
    return getExtraMap();
  }

  /** <code>map&lt;string, string&gt; extra = 11;</code> */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getExtraMap() {
    return internalGetExtra().getMap();
  }

  /** <code>map&lt;string, string&gt; extra = 11;</code> */
  @java.lang.Override
  public /* nullable */ java.lang.String getExtraOrDefault(
      java.lang.String key,
      /* nullable */
      java.lang.String defaultValue) {
    if (key == null) {
      throw new NullPointerException("map key");
    }
    java.util.Map<java.lang.String, java.lang.String> map = internalGetExtra().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }

  /** <code>map&lt;string, string&gt; extra = 11;</code> */
  @java.lang.Override
  public java.lang.String getExtraOrThrow(java.lang.String key) {
    if (key == null) {
      throw new NullPointerException("map key");
    }
    java.util.Map<java.lang.String, java.lang.String> map = internalGetExtra().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, message_);
    }
    com.google.protobuf.GeneratedMessage.serializeStringMapTo(
        output, internalGetDdtags(), DdtagsDefaultEntryHolder.defaultEntry, 2);
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getTimestamp());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(env_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, env_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serviceName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, serviceName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(componentName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, componentName_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, hostname_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, ddsource_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, sourceType_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, status_);
    }
    com.google.protobuf.GeneratedMessage.serializeStringMapTo(
        output, internalGetExtra(), ExtraDefaultEntryHolder.defaultEntry, 11);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, message_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry :
        internalGetDdtags().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String> ddtags__ =
          DdtagsDefaultEntryHolder.defaultEntry
              .newBuilderForType()
              .setKey(entry.getKey())
              .setValue(entry.getValue())
              .build();
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, ddtags__);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(3, getTimestamp());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(env_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, env_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(serviceName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, serviceName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(componentName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, componentName_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, hostname_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, ddsource_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, sourceType_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, status_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry :
        internalGetExtra().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String> extra__ =
          ExtraDefaultEntryHolder.defaultEntry
              .newBuilderForType()
              .setKey(entry.getKey())
              .setValue(entry.getValue())
              .build();
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(11, extra__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.logwise.spark.protobuf.VectorLogs)) {
      return super.equals(obj);
    }
    com.logwise.spark.protobuf.VectorLogs other = (com.logwise.spark.protobuf.VectorLogs) obj;

    if (!getMessage().equals(other.getMessage())) return false;
    if (!internalGetDdtags().equals(other.internalGetDdtags())) return false;
    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (!getTimestamp().equals(other.getTimestamp())) return false;
    }
    if (!getEnv().equals(other.getEnv())) return false;
    if (!getServiceName().equals(other.getServiceName())) return false;
    if (!getComponentName().equals(other.getComponentName())) return false;
    if (hasHostname() != other.hasHostname()) return false;
    if (hasHostname()) {
      if (!getHostname().equals(other.getHostname())) return false;
    }
    if (hasDdsource() != other.hasDdsource()) return false;
    if (hasDdsource()) {
      if (!getDdsource().equals(other.getDdsource())) return false;
    }
    if (hasSourceType() != other.hasSourceType()) return false;
    if (hasSourceType()) {
      if (!getSourceType().equals(other.getSourceType())) return false;
    }
    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus().equals(other.getStatus())) return false;
    }
    if (!internalGetExtra().equals(other.internalGetExtra())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (!internalGetDdtags().getMap().isEmpty()) {
      hash = (37 * hash) + DDTAGS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetDdtags().hashCode();
    }
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    hash = (37 * hash) + ENV_FIELD_NUMBER;
    hash = (53 * hash) + getEnv().hashCode();
    hash = (37 * hash) + SERVICE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getServiceName().hashCode();
    hash = (37 * hash) + COMPONENT_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getComponentName().hashCode();
    if (hasHostname()) {
      hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getHostname().hashCode();
    }
    if (hasDdsource()) {
      hash = (37 * hash) + DDSOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getDdsource().hashCode();
    }
    if (hasSourceType()) {
      hash = (37 * hash) + SOURCE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getSourceType().hashCode();
    }
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    if (!internalGetExtra().getMap().isEmpty()) {
      hash = (37 * hash) + EXTRA_FIELD_NUMBER;
      hash = (53 * hash) + internalGetExtra().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.logwise.spark.protobuf.VectorLogs parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.logwise.spark.protobuf.VectorLogs parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.logwise.spark.protobuf.VectorLogs parseFrom(com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.logwise.spark.protobuf.VectorLogs parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.logwise.spark.protobuf.VectorLogs parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.logwise.spark.protobuf.VectorLogs parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.logwise.spark.protobuf.VectorLogs parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
  }

  public static com.logwise.spark.protobuf.VectorLogs parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.logwise.spark.protobuf.VectorLogs parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.logwise.spark.protobuf.VectorLogs parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.logwise.spark.protobuf.VectorLogs parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);
  }

  public static com.logwise.spark.protobuf.VectorLogs parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.logwise.spark.protobuf.VectorLogs prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /** Protobuf type {@code logcentral.logs.VectorLogs} */
  public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:logcentral.logs.VectorLogs)
      com.logwise.spark.protobuf.VectorLogsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.logwise.spark.protobuf.VectorLogsOuterClass
          .internal_static_logcentral_logs_VectorLogs_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 2:
          return internalGetDdtags();
        case 11:
          return internalGetExtra();
        default:
          throw new RuntimeException("Invalid map field number: " + number);
      }
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 2:
          return internalGetMutableDdtags();
        case 11:
          return internalGetMutableExtra();
        default:
          throw new RuntimeException("Invalid map field number: " + number);
      }
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.logwise.spark.protobuf.VectorLogsOuterClass
          .internal_static_logcentral_logs_VectorLogs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.logwise.spark.protobuf.VectorLogs.class,
              com.logwise.spark.protobuf.VectorLogs.Builder.class);
    }

    // Construct using com.logwise.spark.protobuf.VectorLogs.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        internalGetTimestampFieldBuilder();
      }
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      message_ = "";
      internalGetMutableDdtags().clear();
      timestamp_ = null;
      if (timestampBuilder_ != null) {
        timestampBuilder_.dispose();
        timestampBuilder_ = null;
      }
      env_ = "";
      serviceName_ = "";
      componentName_ = "";
      hostname_ = "";
      ddsource_ = "";
      sourceType_ = "";
      status_ = "";
      internalGetMutableExtra().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.logwise.spark.protobuf.VectorLogsOuterClass
          .internal_static_logcentral_logs_VectorLogs_descriptor;
    }

    @java.lang.Override
    public com.logwise.spark.protobuf.VectorLogs getDefaultInstanceForType() {
      return com.logwise.spark.protobuf.VectorLogs.getDefaultInstance();
    }

    @java.lang.Override
    public com.logwise.spark.protobuf.VectorLogs build() {
      com.logwise.spark.protobuf.VectorLogs result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.logwise.spark.protobuf.VectorLogs buildPartial() {
      com.logwise.spark.protobuf.VectorLogs result =
          new com.logwise.spark.protobuf.VectorLogs(this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.logwise.spark.protobuf.VectorLogs result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.message_ = message_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.ddtags_ = internalGetDdtags();
        result.ddtags_.makeImmutable();
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.timestamp_ = timestampBuilder_ == null ? timestamp_ : timestampBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.env_ = env_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.serviceName_ = serviceName_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.componentName_ = componentName_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.hostname_ = hostname_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.ddsource_ = ddsource_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.sourceType_ = sourceType_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.status_ = status_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.extra_ = internalGetExtra();
        result.extra_.makeImmutable();
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.logwise.spark.protobuf.VectorLogs) {
        return mergeFrom((com.logwise.spark.protobuf.VectorLogs) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.logwise.spark.protobuf.VectorLogs other) {
      if (other == com.logwise.spark.protobuf.VectorLogs.getDefaultInstance()) return this;
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      internalGetMutableDdtags().mergeFrom(other.internalGetDdtags());
      bitField0_ |= 0x00000002;
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      if (!other.getEnv().isEmpty()) {
        env_ = other.env_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getServiceName().isEmpty()) {
        serviceName_ = other.serviceName_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getComponentName().isEmpty()) {
        componentName_ = other.componentName_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.hasHostname()) {
        hostname_ = other.hostname_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (other.hasDdsource()) {
        ddsource_ = other.ddsource_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (other.hasSourceType()) {
        sourceType_ = other.sourceType_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (other.hasStatus()) {
        status_ = other.status_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      internalGetMutableExtra().mergeFrom(other.internalGetExtra());
      bitField0_ |= 0x00000400;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
            case 18:
              {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String> ddtags__ =
                    input.readMessage(
                        DdtagsDefaultEntryHolder.defaultEntry.getParserForType(),
                        extensionRegistry);
                internalGetMutableDdtags()
                    .getMutableMap()
                    .put(ddtags__.getKey(), ddtags__.getValue());
                bitField0_ |= 0x00000002;
                break;
              } // case 18
            case 26:
              {
                input.readMessage(
                    internalGetTimestampFieldBuilder().getBuilder(), extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
            case 34:
              {
                env_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
            case 42:
              {
                serviceName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
            case 50:
              {
                componentName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
            case 58:
              {
                hostname_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
            case 66:
              {
                ddsource_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
            case 74:
              {
                sourceType_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
            case 82:
              {
                status_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000200;
                break;
              } // case 82
            case 90:
              {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String> extra__ =
                    input.readMessage(
                        ExtraDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableExtra().getMutableMap().put(extra__.getKey(), extra__.getValue());
                bitField0_ |= 0x00000400;
                break;
              } // case 90
            default:
              {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int bitField0_;

    private java.lang.Object message_ = "";

    /**
     * <code>string message = 1;</code>
     *
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string message = 1;</code>
     *
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string message = 1;</code>
     *
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      message_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    /**
     * <code>string message = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      message_ = getDefaultInstance().getMessage();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    /**
     * <code>string message = 1;</code>
     *
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      message_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<java.lang.String, java.lang.String> ddtags_;

    private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetDdtags() {
      if (ddtags_ == null) {
        return com.google.protobuf.MapField.emptyMapField(DdtagsDefaultEntryHolder.defaultEntry);
      }
      return ddtags_;
    }

    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableDdtags() {
      if (ddtags_ == null) {
        ddtags_ = com.google.protobuf.MapField.newMapField(DdtagsDefaultEntryHolder.defaultEntry);
      }
      if (!ddtags_.isMutable()) {
        ddtags_ = ddtags_.copy();
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return ddtags_;
    }

    public int getDdtagsCount() {
      return internalGetDdtags().getMap().size();
    }

    /** <code>map&lt;string, string&gt; ddtags = 2;</code> */
    @java.lang.Override
    public boolean containsDdtags(java.lang.String key) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      return internalGetDdtags().getMap().containsKey(key);
    }

    /** Use {@link #getDdtagsMap()} instead. */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getDdtags() {
      return getDdtagsMap();
    }

    /** <code>map&lt;string, string&gt; ddtags = 2;</code> */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getDdtagsMap() {
      return internalGetDdtags().getMap();
    }

    /** <code>map&lt;string, string&gt; ddtags = 2;</code> */
    @java.lang.Override
    public /* nullable */ java.lang.String getDdtagsOrDefault(
        java.lang.String key,
        /* nullable */
        java.lang.String defaultValue) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      java.util.Map<java.lang.String, java.lang.String> map = internalGetDdtags().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    /** <code>map&lt;string, string&gt; ddtags = 2;</code> */
    @java.lang.Override
    public java.lang.String getDdtagsOrThrow(java.lang.String key) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      java.util.Map<java.lang.String, java.lang.String> map = internalGetDdtags().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearDdtags() {
      bitField0_ = (bitField0_ & ~0x00000002);
      internalGetMutableDdtags().getMutableMap().clear();
      return this;
    }

    /** <code>map&lt;string, string&gt; ddtags = 2;</code> */
    public Builder removeDdtags(java.lang.String key) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      internalGetMutableDdtags().getMutableMap().remove(key);
      return this;
    }

    /** Use alternate mutation accessors instead. */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMutableDdtags() {
      bitField0_ |= 0x00000002;
      return internalGetMutableDdtags().getMutableMap();
    }

    /** <code>map&lt;string, string&gt; ddtags = 2;</code> */
    public Builder putDdtags(java.lang.String key, java.lang.String value) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      if (value == null) {
        throw new NullPointerException("map value");
      }
      internalGetMutableDdtags().getMutableMap().put(key, value);
      bitField0_ |= 0x00000002;
      return this;
    }

    /** <code>map&lt;string, string&gt; ddtags = 2;</code> */
    public Builder putAllDdtags(java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableDdtags().getMutableMap().putAll(values);
      bitField0_ |= 0x00000002;
      return this;
    }

    private com.google.protobuf.Timestamp timestamp_;
    private com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp,
            com.google.protobuf.Timestamp.Builder,
            com.google.protobuf.TimestampOrBuilder>
        timestampBuilder_;

    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     *
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) != 0);
    }

    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     *
     * @return The timestamp.
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }

    /** <code>.google.protobuf.Timestamp timestamp = 3;</code> */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
      } else {
        timestampBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    /** <code>.google.protobuf.Timestamp timestamp = 3;</code> */
    public Builder setTimestamp(com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    /** <code>.google.protobuf.Timestamp timestamp = 3;</code> */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)
            && timestamp_ != null
            && timestamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getTimestampBuilder().mergeFrom(value);
        } else {
          timestamp_ = value;
        }
      } else {
        timestampBuilder_.mergeFrom(value);
      }
      if (timestamp_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }

    /** <code>.google.protobuf.Timestamp timestamp = 3;</code> */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000004);
      timestamp_ = null;
      if (timestampBuilder_ != null) {
        timestampBuilder_.dispose();
        timestampBuilder_ = null;
      }
      onChanged();
      return this;
    }

    /** <code>.google.protobuf.Timestamp timestamp = 3;</code> */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetTimestampFieldBuilder().getBuilder();
    }

    /** <code>.google.protobuf.Timestamp timestamp = 3;</code> */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      }
    }

    /** <code>.google.protobuf.Timestamp timestamp = 3;</code> */
    private com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp,
            com.google.protobuf.Timestamp.Builder,
            com.google.protobuf.TimestampOrBuilder>
        internalGetTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ =
            new com.google.protobuf.SingleFieldBuilder<
                com.google.protobuf.Timestamp,
                com.google.protobuf.Timestamp.Builder,
                com.google.protobuf.TimestampOrBuilder>(
                getTimestamp(), getParentForChildren(), isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    private java.lang.Object env_ = "";

    /**
     * <code>string env = 4;</code>
     *
     * @return The env.
     */
    public java.lang.String getEnv() {
      java.lang.Object ref = env_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        env_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string env = 4;</code>
     *
     * @return The bytes for env.
     */
    public com.google.protobuf.ByteString getEnvBytes() {
      java.lang.Object ref = env_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        env_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string env = 4;</code>
     *
     * @param value The env to set.
     * @return This builder for chaining.
     */
    public Builder setEnv(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      env_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    /**
     * <code>string env = 4;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearEnv() {
      env_ = getDefaultInstance().getEnv();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }

    /**
     * <code>string env = 4;</code>
     *
     * @param value The bytes for env to set.
     * @return This builder for chaining.
     */
    public Builder setEnvBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      env_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object serviceName_ = "";

    /**
     * <code>string service_name = 5;</code>
     *
     * @return The serviceName.
     */
    public java.lang.String getServiceName() {
      java.lang.Object ref = serviceName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string service_name = 5;</code>
     *
     * @return The bytes for serviceName.
     */
    public com.google.protobuf.ByteString getServiceNameBytes() {
      java.lang.Object ref = serviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string service_name = 5;</code>
     *
     * @param value The serviceName to set.
     * @return This builder for chaining.
     */
    public Builder setServiceName(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      serviceName_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    /**
     * <code>string service_name = 5;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearServiceName() {
      serviceName_ = getDefaultInstance().getServiceName();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }

    /**
     * <code>string service_name = 5;</code>
     *
     * @param value The bytes for serviceName to set.
     * @return This builder for chaining.
     */
    public Builder setServiceNameBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      serviceName_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object componentName_ = "";

    /**
     * <code>string component_name = 6;</code>
     *
     * @return The componentName.
     */
    public java.lang.String getComponentName() {
      java.lang.Object ref = componentName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        componentName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string component_name = 6;</code>
     *
     * @return The bytes for componentName.
     */
    public com.google.protobuf.ByteString getComponentNameBytes() {
      java.lang.Object ref = componentName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        componentName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string component_name = 6;</code>
     *
     * @param value The componentName to set.
     * @return This builder for chaining.
     */
    public Builder setComponentName(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      componentName_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    /**
     * <code>string component_name = 6;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearComponentName() {
      componentName_ = getDefaultInstance().getComponentName();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }

    /**
     * <code>string component_name = 6;</code>
     *
     * @param value The bytes for componentName to set.
     * @return This builder for chaining.
     */
    public Builder setComponentNameBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      componentName_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object hostname_ = "";

    /**
     * <code>optional string hostname = 7;</code>
     *
     * @return Whether the hostname field is set.
     */
    public boolean hasHostname() {
      return ((bitField0_ & 0x00000040) != 0);
    }

    /**
     * <code>optional string hostname = 7;</code>
     *
     * @return The hostname.
     */
    public java.lang.String getHostname() {
      java.lang.Object ref = hostname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>optional string hostname = 7;</code>
     *
     * @return The bytes for hostname.
     */
    public com.google.protobuf.ByteString getHostnameBytes() {
      java.lang.Object ref = hostname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        hostname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>optional string hostname = 7;</code>
     *
     * @param value The hostname to set.
     * @return This builder for chaining.
     */
    public Builder setHostname(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      hostname_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    /**
     * <code>optional string hostname = 7;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearHostname() {
      hostname_ = getDefaultInstance().getHostname();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }

    /**
     * <code>optional string hostname = 7;</code>
     *
     * @param value The bytes for hostname to set.
     * @return This builder for chaining.
     */
    public Builder setHostnameBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      hostname_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object ddsource_ = "";

    /**
     * <code>optional string ddsource = 8;</code>
     *
     * @return Whether the ddsource field is set.
     */
    public boolean hasDdsource() {
      return ((bitField0_ & 0x00000080) != 0);
    }

    /**
     * <code>optional string ddsource = 8;</code>
     *
     * @return The ddsource.
     */
    public java.lang.String getDdsource() {
      java.lang.Object ref = ddsource_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ddsource_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>optional string ddsource = 8;</code>
     *
     * @return The bytes for ddsource.
     */
    public com.google.protobuf.ByteString getDdsourceBytes() {
      java.lang.Object ref = ddsource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        ddsource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>optional string ddsource = 8;</code>
     *
     * @param value The ddsource to set.
     * @return This builder for chaining.
     */
    public Builder setDdsource(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ddsource_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    /**
     * <code>optional string ddsource = 8;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearDdsource() {
      ddsource_ = getDefaultInstance().getDdsource();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }

    /**
     * <code>optional string ddsource = 8;</code>
     *
     * @param value The bytes for ddsource to set.
     * @return This builder for chaining.
     */
    public Builder setDdsourceBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      ddsource_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object sourceType_ = "";

    /**
     * <code>optional string source_type = 9;</code>
     *
     * @return Whether the sourceType field is set.
     */
    public boolean hasSourceType() {
      return ((bitField0_ & 0x00000100) != 0);
    }

    /**
     * <code>optional string source_type = 9;</code>
     *
     * @return The sourceType.
     */
    public java.lang.String getSourceType() {
      java.lang.Object ref = sourceType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>optional string source_type = 9;</code>
     *
     * @return The bytes for sourceType.
     */
    public com.google.protobuf.ByteString getSourceTypeBytes() {
      java.lang.Object ref = sourceType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        sourceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>optional string source_type = 9;</code>
     *
     * @param value The sourceType to set.
     * @return This builder for chaining.
     */
    public Builder setSourceType(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      sourceType_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    /**
     * <code>optional string source_type = 9;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearSourceType() {
      sourceType_ = getDefaultInstance().getSourceType();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }

    /**
     * <code>optional string source_type = 9;</code>
     *
     * @param value The bytes for sourceType to set.
     * @return This builder for chaining.
     */
    public Builder setSourceTypeBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      sourceType_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";

    /**
     * <code>optional string status = 10;</code>
     *
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000200) != 0);
    }

    /**
     * <code>optional string status = 10;</code>
     *
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>optional string status = 10;</code>
     *
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>optional string status = 10;</code>
     *
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      status_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    /**
     * <code>optional string status = 10;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }

    /**
     * <code>optional string status = 10;</code>
     *
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<java.lang.String, java.lang.String> extra_;

    private com.google.protobuf.MapField<java.lang.String, java.lang.String> internalGetExtra() {
      if (extra_ == null) {
        return com.google.protobuf.MapField.emptyMapField(ExtraDefaultEntryHolder.defaultEntry);
      }
      return extra_;
    }

    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableExtra() {
      if (extra_ == null) {
        extra_ = com.google.protobuf.MapField.newMapField(ExtraDefaultEntryHolder.defaultEntry);
      }
      if (!extra_.isMutable()) {
        extra_ = extra_.copy();
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return extra_;
    }

    public int getExtraCount() {
      return internalGetExtra().getMap().size();
    }

    /** <code>map&lt;string, string&gt; extra = 11;</code> */
    @java.lang.Override
    public boolean containsExtra(java.lang.String key) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      return internalGetExtra().getMap().containsKey(key);
    }

    /** Use {@link #getExtraMap()} instead. */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getExtra() {
      return getExtraMap();
    }

    /** <code>map&lt;string, string&gt; extra = 11;</code> */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getExtraMap() {
      return internalGetExtra().getMap();
    }

    /** <code>map&lt;string, string&gt; extra = 11;</code> */
    @java.lang.Override
    public /* nullable */ java.lang.String getExtraOrDefault(
        java.lang.String key,
        /* nullable */
        java.lang.String defaultValue) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      java.util.Map<java.lang.String, java.lang.String> map = internalGetExtra().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }

    /** <code>map&lt;string, string&gt; extra = 11;</code> */
    @java.lang.Override
    public java.lang.String getExtraOrThrow(java.lang.String key) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      java.util.Map<java.lang.String, java.lang.String> map = internalGetExtra().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearExtra() {
      bitField0_ = (bitField0_ & ~0x00000400);
      internalGetMutableExtra().getMutableMap().clear();
      return this;
    }

    /** <code>map&lt;string, string&gt; extra = 11;</code> */
    public Builder removeExtra(java.lang.String key) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      internalGetMutableExtra().getMutableMap().remove(key);
      return this;
    }

    /** Use alternate mutation accessors instead. */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMutableExtra() {
      bitField0_ |= 0x00000400;
      return internalGetMutableExtra().getMutableMap();
    }

    /** <code>map&lt;string, string&gt; extra = 11;</code> */
    public Builder putExtra(java.lang.String key, java.lang.String value) {
      if (key == null) {
        throw new NullPointerException("map key");
      }
      if (value == null) {
        throw new NullPointerException("map value");
      }
      internalGetMutableExtra().getMutableMap().put(key, value);
      bitField0_ |= 0x00000400;
      return this;
    }

    /** <code>map&lt;string, string&gt; extra = 11;</code> */
    public Builder putAllExtra(java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableExtra().getMutableMap().putAll(values);
      bitField0_ |= 0x00000400;
      return this;
    }

    // @@protoc_insertion_point(builder_scope:logcentral.logs.VectorLogs)
  }

  // @@protoc_insertion_point(class_scope:logcentral.logs.VectorLogs)
  private static final com.logwise.spark.protobuf.VectorLogs DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.logwise.spark.protobuf.VectorLogs();
  }

  public static com.logwise.spark.protobuf.VectorLogs getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VectorLogs> PARSER =
      new com.google.protobuf.AbstractParser<VectorLogs>() {
        @java.lang.Override
        public VectorLogs parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

  public static com.google.protobuf.Parser<VectorLogs> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VectorLogs> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.logwise.spark.protobuf.VectorLogs getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
