// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: logwise-vector.proto
// Protobuf Java Version: 4.33.0

package com.logwise.spark.protobuf;

@com.google.protobuf.Generated
public interface VectorLogsOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:logwise.vector.logs.VectorLogs)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string service_name = 1;</code>
   *
   * @return The serviceName.
   */
  java.lang.String getServiceName();
  /**
   * <code>string service_name = 1;</code>
   *
   * @return The bytes for serviceName.
   */
  com.google.protobuf.ByteString getServiceNameBytes();

  /**
   * <code>string message = 2;</code>
   *
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   *
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString getMessageBytes();

  /**
   * <code>string log_level = 3;</code>
   *
   * @return The logLevel.
   */
  java.lang.String getLogLevel();
  /**
   * <code>string log_level = 3;</code>
   *
   * @return The bytes for logLevel.
   */
  com.google.protobuf.ByteString getLogLevelBytes();

  /**
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   *
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   *
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /** <code>.google.protobuf.Timestamp timestamp = 4;</code> */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();
}
